import type { Metadata } from "next";
import "./globals.css";

import SessionWrapper from "./components/SessionWrapper";

export const metadata: Metadata = {
  title: "SportsPartner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="light">{children}</body>
      </html>
    </SessionWrapper>
  );
}
